name: Publish the Lichess API Demo app
on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run prod
      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add dist -f
          git commit -m 'Deploy to GitHub Pages'
          git push origin `git subtree split --prefix dist master`:gh-pages --force
